---
apiVersion: k3d.io/v1alpha5
kind: Simple
metadata:
  name: k3s-airgap
servers: 1
agents: 0
image: k3s:airgap
network: k3d-airgap
registries:
  config: |
    mirrors:
      "hauler.internal":
        endpoint:
          - http://k3d-jumpbox:5000